config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :payments
  root 'invoices#index'
  get 'checkout/:invoice_id' => "payments#checkout", as: 'checkout'
  post '/create-payment-intent', to: "payments#create_payment_intent"
  get 'payment_status' => 'payments#status'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:amount, :description)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]
  layout 'layouts/checkout', only: [:checkout, :status, :create_payment_intent]
  skip_before_action :verify_authenticity_token, only: [:checkout, :create_payment_intent]


  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def checkout

  end

  def status
    puts "====params===#{params[:redirect_status]}==="
    @status = params[:redirect_status]
  end

  def create_payment_intent
    puts "============creating_payment_intent===================="
    @invoice = Invoice.find(params[:invoice_id])
    invoice_amount = @invoice.amount #9000 #in cents
    stripe_fee_amount = (invoice_amount * 0.029) + 30 #US Stripe Fees in cents for Card-Payment: Formula : (2.9% + $0.30)
    app_fee_amount = stripe_fee_amount + 100 #in cents

    params = {
      amount: invoice_amount.round,  #Required # amount is in Cent : So here, 1.09 USD
      currency: 'USD', #Required
      payment_method_types: ['card', 'us_bank_account'], #us_bank_account => This is ACH direct debit payment
      statement_descriptor: 'Invoice transaction',
      application_fee_amount: app_fee_amount.round, #this is in cent
      description: '3-Making payment from demo client to demo vendor - web',
      receipt_email: 'recipient@example.com', # Client / company email
      metadata: {
        invoice_id: 1,
        pay_from_connected_account_id: 'acct_1LMtFSRClzJSUu73',
        pay_from_uc_company_id: 1,
      },
      transfer_data: {
        destination: 'acct_1LMxuHRSKLI1b44n', #Vendor or Broker accountId
      },
      # on_behalf_of: 'acct_1LMAcsROvpuZ9HoV' # Connected Account ID - client
    }
    begin
      payment_intent = Stripe::PaymentIntent.create(params)
      puts "-----Intent------#{payment_intent.inspect}---"
      render json: { clientSecret: payment_intent.client_secret }
    rescue Stripe::CardError => e
      render json: { error: "A payment card error occurred: #{e.message}" }, status: :not_found
    rescue Stripe::InvalidRequestError => e
      render json: { error: "An invalid request occurred: #{e.message}" }, status: :bad_request
    rescue Stripe::StripeError => e
      render json: { error: "Another problem occurred, maybe unrelated to Stripe: #{e.message}" }, status: :bad_request
    rescue Stripe::APIError => e
      render json: { error: "Stripe API server error: #{e.message}" }, status: :internal_server_error
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/invoices/_form.html.erb
<%= form_with(model: invoice) do |form| %>
  <% if invoice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/_invoice.html.erb
<div id="<%= dom_id invoice %>">

  <p>
    <strong>Description:</strong>
    <%= invoice.description %>
  </p>


  <p>
    <strong>Amount:</strong>
    <%= invoice.amount %> cents
  </p>

  <p>
    <%= link_to "Make Payment: $#{(invoice.amount/100.0).round}", checkout_path(invoice.id) %>
  </p>

</div>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Show this invoice", @invoice %> |
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/index.html.erb
<p style="color: green"><%= notice %></p>

<!-- <h1>Invoices</h1> -->

<div id="invoices">
  <% @invoices.each do |invoice| %>
    <%= render invoice %>
    <p>
      <%= link_to "Show this invoice", invoice %>
    </p>
  <% end %>
</div>

<%= link_to "New invoice", new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @invoice %>

<div>
  <%= link_to "Edit this invoice", edit_invoice_path(@invoice) %> |
  <%= link_to "Back to invoices", invoices_path %>

  <%= button_to "Destroy this invoice", @invoice, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stripe-Ruby-JS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/checkout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>
      Accept a payment
    </title><meta content="A demo of a payment on Stripe" name="description" />
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <link href="/assets/checkout.css" rel="stylesheet" />
    <script src="https://js.stripe.com/v3/"></script>

  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

</div>

app/views/payments/checkout.html.erb
<script defer="" src="/assets/checkout.js"></script>
<form id="payment-form">
  <div id="payment-element">
  </div>
  <button id="submit">
    <div class="spinner hidden" id="spinner">
    </div>
    <span id="button-text">
      Pay now
    </span></button>
  <div class="hidden" id="payment-message">
  </div>
</form>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>

app/views/payments/status.html.erb
<p>
  <%= link_to "GO HOME", root_path %> | Payment Status: <%= @status %>
</p>